// AUTH
export const START_LOGIN = "START_LOGIN";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const FAIL_LOGIN = "FAIL_LOGIN";

export const START_LOGOUT = "START_LOGOUT";
export const SUCCESS_LOGOUT = "SUCCES_LOGOUT";

export const SUCCESS_GET_SESSIONS = "SUCCES_GET_SESSIONS";
export const FAIL_GET_SESSIONS = "FAIL_GET_SESSIONS";

// ALERT
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
